version: '2'

services:
  app:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      environment:
        POSTGRES_USER: vitorbelluzzo
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: login_database